name: Run-Clippy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: sudo apt update && sudo apt install -y libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
